#' Tits nestling data (cleaned version)
#'
#' This is the cleaned dataset from the first part of the "tits reproduction study" of the PubPrivLands
#' project containing observations for the Great tits (\emph{Parus major}) and Blue tits (\emph{Cyanistes
#' caeruleus}) nestlings aggregated at the nestbox level for each year of study. \cr
#' This dataset was generated by the first group of functions of the `{ppl.tits}` package that cleaned and
#' prepared all raw data linked to tits breeding or local environmental conditions. This dataset thus
#' contains the \strong{response} variables related to tits' \emph{reproduction success} and
#' \emph{physical condition}, as well as all potential \strong{explanatory} variables and \strong{covariates}
#' that could be used for analysis, with the exception of the \emph{connectivity} metrics that will be
#' computed by the second group of functions of the package, giving the `final tits dataset` (LINK?***). \cr
#'
#' For further details regarding data acquisition, processing or metadata, readers are referred to: i) the
#' documentation of the `{ppl.tits}` package functions and related reports (cf. the package's
#' [README file](https://github.com/mrelnoob/ppl.tits); ii) the associated article's Materials & Methods
#' section; and iii) the articles's Supplementary Materials (LINKS?***).
#'
#' @format ## `ntits_clean`
#' A data frame (tibble) with 406 rows and 47 columns. Here's
#' \describe{
#'   \item{\strong{id_nestbox}}{The nestbox ID (categorical).}
#'   \item{iso2, iso3}{2 & 3 letter ISO country codes}
#'   \item{year}{Year}
#'   ...
#' }
#' @source <https://github.com/mrelnoob/ppl.tits>
"ntits_clean"
